
:host = http://localhost:8765

#######################
## General endpoints ##
#######################

# Get the currently running version
GET :host/api/version

# Ping
POST :host/api/ping

############################
## Raw IrSignal endpoints ##
############################

# Get the last received IR signal
# Response body:
# {
#   "signal": infrared signal
# }
GET :host/api/signal/latest-received

# Send a IR signal
POST :host/api/signal/send
Content-Type: application/json
{
  "protocol": "RC6",
  "value": "0xC",
  "bits": 20,
  "address": "0x0"
}
