
:host = http://localhost:8765

#######################
## General endpoints ##
#######################

# Get the currently running version
GET :host/api/version

# Ping
POST :host/api/ping

############################
## Raw IrSignal endpoints ##
############################

# Get the last received IR signal
# Response body:
# {
#   "signal": infrared signal
# }
GET :host/api/signal/latest-received

# Send a IR signal
POST :host/api/signal/send
Content-Type: application/json
{
  "protocol": "RC6",
  "value": "0xC",
  "bits": 20,
  "address": "0x0"
}

# Get all named signals
GET :host/api/named-signal

# Refresh all named signals from disk
POST :host/api/named-signal/refresh

# Save last received signal as name
:name = null
POST :host/api/named-signal/save-latest-received?name=:name

# Save a signal as name
:name = foo
PUT :host/api/named-signal/:name
Content-Type: application/json
{
  "protocol": "RC6",
  "value": "0xC",
  "bits": 20,
  "address": "0x0"
}

# Send signal by name
:name = null
POST :host/api/named-signal/:name/send

# Delete signal by name
:name = foo
DELETE :host/api/named-signal/:name